title: MMB Status
buildFuture: true
defaultContentLanguage: en
languageCode: it
baseURL: https://status.yap.mmb.software/
params:
  disableDarkMode: true
  shortDateFormat: 15:04 — Jan 2
  down: "#e60000"
  systems:
    - name: Gateway
      category: Uncategorized
    - name: Backup Gateway
      category: Uncategorized
    - name: API
      description: The guts of the application.
      category: Uncategorized
    - name: Media Proxy
      description: This is the service responsible for serving images, audio, and
        video. It is reliant on our CDN.
      category: Uncategorized
    - name: webclient
      category: YAP
      displayName: Applicazione
    - name: fe
      category: YAP
      displayName: e-bill
    - name: api-export
      category: YAP
      displayName: API Export
    - name: api-int
      category: YAP
      displayName: API Integration
    - name: pcp
      category: YAP
      displayName: PCP
      description: API per il corretto funzionamento del PCP
    - name: yapds
      category: YAP
      displayName: YAPDs
      description: API per il corretto funzionamento di YAPDs
    - name: wsnet
      category: YAP
      displayName: Workshop.NET
      description: API per il corretto funzionamento di Workshop.NET
    - name: comunicazioni
      category: YAP
      displayName: Comunicazioni
    - name: ced
      category: YAP
      displayName: CED
      description: Servizi di ricerca per targa e normalizzazioni
    - name: kromeda
      category: YAP
      displayName: Kromeda
      description: Servizi di integrazione con Kromeda
    - name: stampe
      category: YAP
      displayName: Stampe
      description: Servizi di generazione delle stampe
  dateFormat: January 2, 2006 at 3:04 PM
  brand: "#F0F0F0"
  headerTextColor: white
  logo: /logo.png
  incidentPostsPerPage: 10
  googleAnalytics: UA-00000000-1
  customTabs: []
  alwaysKeepBrandColor: true
  disableComplexCalculations: false
  useLogo: false
  disrupted: "#cc4400"
  notice: "#24478f"
  incidentHistoryFormat: monthly
  disableIncidentHistory: false
  ok: "#008000"
  categories:
    - name: Uncategorized
      untitled: true
    - name: YAP
      closed: false
    - name: WS
      closed: false
  description: We continuously monitor the status of our services and if there are
    any interruptions, a note will be posted here.
  enableCustomHTML: false
  useLargeHeaderDesign: false
theme: cstate
preserveTaxonomyNames: true
taxonomies:
  affected: affected
outputs:
  page:
    - html
    - json
  section:
    - html
    - json
    - rss
  home:
    - html
    - json
    - rss
    - svg
outputFormats:
  svg:
    isPlainText: true
    mediaType: image/svg+xml
